# Generated by Django 4.1 on 2022-09-01 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0002_alter_country_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название отеля')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='hotel_image', verbose_name='Фото отеля')),
                ('hotel_type', models.CharField(choices=[('Хостел', 'Хостел'), ('Гостиница', 'Гостиница'), ('Отель', 'Отель'), ('Апартаменты', 'Апартаменты'), ('Аренда', 'Аренда')], default='Отель', max_length=100)),
                ('phone', models.CharField(default='+996 708 89 03 08', max_length=100)),
                ('restaurant', models.CharField(choices=[('Yes', 'Yes'), ('Not', 'Not')], default='Not', max_length=10)),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Автогенерация URL')),
                ('valid', models.BooleanField(default=True, verbose_name='Работает')),
                ('price', models.PositiveIntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_from_country', to='countries.country')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Рестораны',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='second_restaurant_image/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_image', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Дополнительная фотография',
                'verbose_name_plural': 'Дополнительные фотографии',
            },
        ),
    ]
