# Generated by Django 4.1 on 2022-09-05 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotel_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImage',
            new_name='HotelImage',
        ),
    ]
