# Generated by Django 4.1 on 2022-09-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_rename_postimage_hotelimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='restaurant',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Not', max_length=10),
        ),
    ]
