# Generated by Django 4.1 on 2022-09-09 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_places_hotel'),
        ('hotels', '0004_alter_hotel_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='country',
        ),
        migrations.AddField(
            model_name='hotel',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotels_in_place', to='places.places'),
            preserve_default=False,
        ),
    ]
