# Generated by Django 4.1 on 2022-09-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='second_logo',
            field=models.ImageField(default=1, upload_to='second_logo/', verbose_name='second logo'),
            preserve_default=False,
        ),
    ]
