# Generated by Django 4.1 on 2022-09-16 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0002_setting_second_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Сообщение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to_message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение Админу',
                'verbose_name_plural': 'Сообщения Админам',
            },
        ),
    ]
