# Generated by Django 4.1 on 2022-09-16 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0003_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='Почта')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('phone', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('problem', models.TextField(verbose_name='Проблема')),
                ('status', models.CharField(choices=[('В ожидании', 'В ожидании'), ('Решена', 'Решена'), ('Не решена', 'Не решена')], default='В ожидании', max_length=30, verbose_name='Статус обращения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение Админу',
                'verbose_name_plural': 'Сообщения Админу',
            },
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
