# Generated by Django 4.1 on 2022-09-06 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0003_rename_image_country_country_image'),
        ('hotels', '0004_alter_hotel_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название места')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Автогенерация URL')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places_from_country', to='countries.country')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hotels', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='second_place_image/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_image', to='places.places')),
            ],
            options={
                'verbose_name': 'Дополнительная фотография',
                'verbose_name_plural': 'Дополнительные фотографии',
            },
        ),
    ]
