# Generated by Django 4.1 on 2022-09-06 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='image',
            field=models.ImageField(default=1, upload_to='place_image', verbose_name='Фото места'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_place', to='places.places'),
        ),
    ]
