# Generated by Django 4.1 on 2022-09-03 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_alter_country_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='image',
            new_name='country_image',
        ),
    ]
